### ISSUE TITLE
出现崩溃

### ISSUE THREAD

**Issue by zou145688zhuang** [SYFH/FKDownloader#1]
运行出现崩溃，崩溃在
![2018-11-27 9 45 12](https://user-images.githubusercontent.com/11897056/49053028-59dc7080-f229-11e8-902c-d07c9482817b.png)

**Comment by SYFH** [comment]
能说一下具体的设备型号和系统版本吗?

**Comment by SYFH** [comment]
这个修复方法是在 [stackoverflow](https://stackoverflow.com/questions/39346231/resume-nsurlsession-on-ios10) 找到的, 但没有边界处理还是挺令人意外的, 现在已经添加上边界处理并更新了版本.
感谢您找出这个 BUG, 毕竟我在 iPhone 8p iOS 12.1 上并没有遇见这个问题

**Comment by zou145688zhuang** [comment]
点击全部开始再点击全部结束崩溃，你的数组取值要进行安全
- (id)safeObjectAtIndex:(NSUInteger)index
{
    if (self.count > index)
    {
        return [self objectAtIndex:index];
    }
    return nil;
}
![2018-11-27 7 32 45](https://user-images.githubusercontent.com/11897056/49079351-4954e600-f27b-11e8-8e01-164959df56d3.png)

**Comment by zou145688zhuang** [comment]
模拟器iPhone8p iOS12.1，xcode10

**Comment by SYFH** [comment]
诶, iOS 就是太多变. 这回得好好研究一下 iOS resumeData 的封解包了, 等待下一次版本更新吧, 现在只是暂时规避了一下而已, 问题还是会存在的.

**Comment by SYFH** [comment]
可以了, 已经修复好 ResumeData 封解包的问题了, 现在只能祈祷 iOS 12 之后的版本 ResumeData 的归档 top key 不再更改了😓
