### ISSUE TITLE
taskIdentifierIgnoreParameters = NO 后运行闪退

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#11]
我在Demo 的 `urls` 中添加了一些相同的地址
![image](https://user-images.githubusercontent.com/10528244/49991570-79f78800-ffbc-11e8-8088-5b7ea9eea685.png)
并给每个任务设置了不同的名字：
![image](https://user-images.githubusercontent.com/10528244/49991587-8da2ee80-ffbc-11e8-93d6-344fc2b04159.png)
然后 `askIdentifierIgnoreParameters = NO; `，运行 Demo 会闪退

**Comment by SYFH** [comment]
`taskIdentifierIgnoreParameters` 相关设置将在下一版本中废弃, 因为会造成同一个 URL 不同的 Identifier, 同样的, 也会在设置 `autoCoding = NO` 时, 导致后台下载任务的恢复数据文件命名错乱, 目前任务的 Identifier 会通过 URL 整体生成.
