### ISSUE TITLE
task 过多主线程卡顿

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#12]
当添加很多 task（没办法，M3U8列表的下载一次下载至少200个请求地址）

```
[[FKDownloadManager manager].taskHub.allTask orderEach:^(FKTask *task, NSUInteger idx) {
        [[FKDownloadManager manager] start:task.url];
    }];
```
遍历执行 start 方法后

![image](https://user-images.githubusercontent.com/10528244/50050081-db3e6900-012c-11e9-8d68-717149c97134.png)

由于这里将 task 返回到了主线程，过多的 task 会造成界面卡顿。

**Comment by SYFH** [comment]
0.1.2 版本去除了可能会频繁切换线程代码, 现在只保留了线程锁, 线程调度和切换全部由业务层决定.
Demo 中可以测试一次性添加超多任务的需求, 可以将添加任务组包含到子线程中, 再用 `-[FKDownloadManager addedBlock]` 获取一添加完任务后事件来刷新 UI.
我已在模拟器中测试过在子线程中一次性添加 5000 个任务, 基本上 CPU 瞬间飙升到 70% 后又回落至 1%, 内存上涨 20 MB 左右, 恒定 1% 是因为有 Timer 运行(可以配置 `calculateSpeedWithEstimated = NO` 关闭), 20 MB 是任务的内存缓存.
目前的 Timer 已经从 NSTimer 替换成 GCD Timer, 否则 5000 个任务的 Timer 将恒定占用 30% 左右的 CPU.
