### ISSUE TITLE
task 暂停状态不正确

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#13]
调用 task 的 suspend 方法没有调用 `sendSuspendInfo` 方法将 status 置为 `TaskStatusSuspend` ，会导致在有任务是强制重启 `restore` 方法报错

![image](https://user-images.githubusercontent.com/10528244/50050768-c4554200-013f-11e9-9bb5-3f43ad065ba3.png)

**Comment by SYFH** [comment]
可以说一下操作流程和具体参数吗?
删除 Demo App 后进行同样的操作还会出现同样的问题吗?

**Comment by huanglins** [comment]
一般情况下添加比较少的请求都是正常的，大部分的问题是因为我一次性添加过多任务（200+），执行过程中瞬间将主线程卡死引起的。卡死后重启APP，也出现了之前的 `Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"` 错误。我不确定是哪一块引起的，因为已经卡死了，后面我测试后再给你反馈。
