### ISSUE TITLE
url.encodeEscapedString 下载错误

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#16]
我这边测试发现一些请求地址先编码后会请求错误，去掉编码后可以正常请求成功。不知道这个操作是否必须？

**Comment by SYFH** [comment]
为了兼容特殊字符，内部已经做过编码了，外部调用可以直接使用原始 URL，避免二次编码造成一些错误.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: vincent <notifications@github.com>
发送时间: 星期二, 十二月 18, 2018 10:25 上午
收件人: SYFH/FKDownloader
抄送: Subscribed
主题: [SYFH/FKDownloader] url.encodeEscapedString 下载错误 (#16)


我这边测试发现一些请求地址先编码后会请求错误，去掉编码后可以正常请求成功。不知道这个操作是否必须？

―

**Comment by huanglins** [comment]
在 task 的 ready 方法中
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:[self.url encodeEscapedString]]];   这里对 url 进行了编码。

我这边测试发现，有些请求地址编码后会无法下载，去掉后就能正常下载。这里可以进行兼容下吗？

**Comment by huanglins** [comment]
我这边测试发现，还是得去掉编码才能使用。

**Comment by SYFH** [comment]
已修改为递归式解码, 先解码再编码.

**Comment by huanglins** [comment]
我这边测试加上编码后会不正确，不正确的地址差不多这样:
```
http://122.72.99.57/a21abf2c04869d3340f76d77f16fe3fd.ts?ts_name=23&type=mpptv.wp&vvid=5e7d48c1-271f-bbf6-8af1-235930b445f4&k=f4383d4a83fde9a57685d39dceccaa2f-d2fc-1545249610%26segment%3D7898ee86_789804e6_1545235210%26bppcataid%3D980
```

**Comment by SYFH** [comment]
还是被系统方法坑了, 它会把 `http://` 和 `/ ` 也编码了, 现在改成与 AFN 相同的模式, 单独将参数进行编码.
之后我会添加一些单元测试以覆盖一些问题
