### ISSUE TITLE
task.isFinish 的 progress 的建议

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#17]
```
- (void)reday {
    FKLog(@"开始准备: %@", self)
    
    if (self.isFinish) {
        self.progress.totalUnitCount = 1;
        [self sendFinishInfo];
        return;
    }
...
```

当 task 的文件已经完成时，建议将文件的大小作为 progress 的 totalUnitCount

**Comment by SYFH** [comment]
这里赋值为 1 是因为创建一个已下载完成的 task 时, 让它变成 100% 进度, 从父 NSProgress 移除.
这一段代码算是遗留吧, 已经废弃了, 因为在子 NSProgress 成为 100% 时, 修改 totalUnitCount 会导致父 NSProgress 重新 pending 一次子 NSProgress 的设定值, 就会出现父 NSProgress 的进度出现异常.
现在已移除类似代码, 子 NSProgress 在创建时, totalUnitCount 默认为 100, 在赋值 URL 时判断是否是已完成任务, 是则 `self.progress.completedUnitCount = self.progress.totalUnitCount` 来标记完成.

**Comment by huanglins** [comment]
有个问题是，比如我添加200个任务，下载完成30个以后重启app，重新进行添加任务操作，它的任务进度会从0开始，但是实际已经完成30个了。

**Comment by SYFH** [comment]
这回的提交就是解决这个问题的, 在赋值 URL 时判断是否是已完成任务, 是则 `sendFinishInfo`, 然后在 `sendFinishInfo` 内 `self.progress.completedUnitCount = self.progress.totalUnitCount` 让进度达到 100 %, 更新代码后可以在测试一下, 这回的提交还没有添加 tag, 如果没问题就会更新版本.
