### ISSUE TITLE
restory 报错

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#18]
![image](https://user-images.githubusercontent.com/10528244/50142141-4e3e1000-02e4-11e9-897f-5cc8c8eaa88c.png)

下载中强制重启app，`- (void)restore:(NSURLSessionDownloadTask *)task` 方法中，`self.resumeData` 为 nil 时会报错

**Comment by SYFH** [comment]
是我疏忽了, 毕竟之前挺依赖归档信息的, 现在已修改逻辑, 会提前判空, 如为空会先 ready 后 execute.
