### ISSUE TITLE
支持多种下载任务列表管理

### ISSUE THREAD

**Issue by Roen-Ro** [SYFH/FKDownloader#2]
正打算自己写一个，发现你的这个框架，可以节省不少工作
想问一下你这边如对多种任务下载队列进行管理呢，比如我一个app里面，既有电影下载，又有音乐下载，这是两种不同的任务，都需要后台下载

**Comment by SYFH** [comment]
emmm 文件类型是没有上限的, 而且您这个需求偏向针对性, 所以最好是自己进行管理, 而不是依赖下载库来实现, 比如 key: url, value: type 这样储存信息.
也许以后我会添加诸如`按 tag 进行分组操作` 的功能, 但优先级并不高.

**Comment by huanglins** [comment]
+1
比如 m3u8 文件，这种单个任务是很多单个 request 组成的。

**Comment by SYFH** [comment]
0.0.15 版本将 tag 相关的操作添加上了, 但目前只有最简单的操作, `-[FKTask addTags:]`, `-[FKTask removeTags:]`, `-[FKDownloadManager acquireWithTag:]`和 `FKTaskInfoTags` key.
各位还有什么想要添加的基本操作吗? 
现在大部分的功能快要基本完善了, 完善后就是 `1.0.0` 版本了

**Comment by SYFH** [comment]
1. 单独设置恢复数据保存路径和文件保存路径, 这个需求没毛病
2. tags 的汇总状态回调可以详细说一下吗?

**Comment by SYFH** [comment]
总任务进度的实现有瑕疵, 已经修复了, 并且添加了一个总任务进度的 Blok.
0.0.16 版本已经支持获取一组任务的总进度了, 可以使用 `[[FKDownloadManager manager] acquireWithTag:@"tag"].groupProgress` 这种方法获取组任务的 NSProgress.
唯一的缺点就是文件总大小无法在第一时间全部获取, 只有进行过的任务才可获取准确的 Conten-Length.

**Comment by SYFH** [comment]
0.0.17 版本把组进度不准确的问题解决了, 方案是使用固定大小与完成百分比计算的, 即使有的任务 Conten-Length 为 0 也可以正确包含并计算了
