### ISSUE TITLE
task 定时器问题

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#20]
![image](https://user-images.githubusercontent.com/10528244/50202179-1db7ae00-0398-11e9-88d3-0432677b7cb0.png)

当 task 重建定时器时，有概率会出现这个 crash ，有时是上面这里，有时是下面 
```
dispatch_source_cancel(self.timer);
```

**Comment by SYFH** [comment]
是因为 self.timer 已经有值或为 NULL 造成的, 现已添加判断逻辑.
