### ISSUE TITLE
一个 task 每秒下载速度计算的小问题

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#21]

**Comment by huanglins** [comment]
当我添加一些任务，单个任务文件比较小，定时器还未在 TaskStatusExecuting 中执行成功，就已经下载完成，这时下载速度为0。当放到一组任务下查看时，就会看到每秒下载速度一直为 0。

**Comment by huanglins** [comment]
![image](https://user-images.githubusercontent.com/10528244/50205052-e3530e80-03a1-11e9-8077-ab1afae4f84c.png)

**Comment by SYFH** [comment]
可以的, 方法采用了, 其实像这种已验证无误的代码, 你可以 fork 后直接 pull request 的.
