### ISSUE TITLE
下载完成后拷贝文件到指定目录报："No such file"

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#23]
https://stackoverflow.com/questions/20251432/cant-move-file-after-background-download-no-such-file

这个地址用 NSData 替换 `fileManager` 的 copyItemAtPath` 可以解决

**Comment by huanglins** [comment]
```
Domain=NSCocoaErrorDomain Code=4 "The file “CFNetworkDownload_Bo7EK8.tmp” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/7CE50869-630E-46A4-A4B1-A9DCD660EEF6/Library/Caches/com.apple.nsurlsessiond/Downloads/com.xx.xx/CFNetworkDownload_Bo7EK8.tmp, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/DB6E188C
```

好像还是没解决

**Comment by huanglins** [comment]
根本原因是每次启动沙盒路径会变：
![image](https://user-images.githubusercontent.com/10528244/50211795-75fca900-03b4-11e9-9170-7638e3d6881a.png)
在这里重新去检测一次路径，获取有其他的实现方式。

**Comment by SYFH** [comment]
最根本还是因为归档将路径保存了, 而在沙盒中, 路径是一直变化的, 这个问题在两三个版本前就已经标记 TODO 了, resume data 的 NSURLSessionResumeInfoLocalPath 也会造成同样的问题.
现已解决, 在 task 设置 info 时会更新路径, 在使用 resume data 时也会更新路径字段.
目前是倒序 path components 后根据 UUID 判断获取沙盒内路径, 然后重新使用 home path 拼接正确路径的.
