### ISSUE TITLE
task 下载完成后删除任务崩溃

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#24]
当我添加一组任务，全部下载完成后我想清除这些任务，因为自己另外做了汇总的存储，同时也避免 task 中的任务过多。我在 `didFinishTask` 的回调中判断这组任务的数量是否全部下载完成，然后调用：
```
[[[FKDownloadManager manager] acquireWithTag:targetId] forEach:^(FKTask * _Nonnull obj, NSUInteger idx) {
                    [[FKDownloadManager manager] remove:obj.url];
                }];
```
并开始下一组任务，这样操作好像是不安全的，我已遇到过两种错误（一定概率下）：
![image](https://user-images.githubusercontent.com/10528244/50258154-522f7680-0439-11e9-8a6c-4a08ba029077.png)
还有一种：
`[FKTask retain]: message sent to deallocated instance 0x2812dcd20`

**Comment by SYFH** [comment]
嗯, 应该是 KVO 没有处理线程安全的问题, 我会在之后的版本修复

**Comment by SYFH** [comment]
来使用新版本吧, 如果还是有类似的问题, 请提交新的 Issue😉
