### ISSUE TITLE
切换一组任务的暂停/恢复任务的状态的问题

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#25]
切换一组任务的暂停/恢复任务几次后，其中的单个任务下载完成后执行下一个任务时会没有任何响应，不会响应下载的回调，也不会出错。操作一次就能下载成功一个任务，但下一个不会自动开始。

暂停
```
[[[FKDownloadManager manager] acquireWithTag:xx] forEach:^(FKTask * _Nonnull obj, NSUInteger idx) {
                    [[FKDownloadManager manager] suspend:obj.url];
                }];
```
恢复
```
[[[FKDownloadManager manager] acquireWithTag:xx] forEach:^(FKTask * _Nonnull obj, NSUInteger idx) {
                    [[FKDownloadManager manager] resume:obj.url];
                }];
```

**Comment by huanglins** [comment]
![image](https://user-images.githubusercontent.com/10528244/50323825-89c02080-0516-11e9-9397-f1ca0be2edbe.png)
我在 task 的 refreshSpeed 方法中加入了这个判断，能暂时解决我的问题。不知道是否有更好的办法。

**Comment by SYFH** [comment]
emmm 最近事有点多, 之后我直接找一些 m3u8 大量测试一下, 可能会需要一些时间, 先标记一下

**Comment by SYFH** [comment]
来使用新版本吧, 如果还是有类似的问题, 请提交新的 Issue😉
