### ISSUE TITLE
task timer 报错

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#26]
![image](https://user-images.githubusercontent.com/10528244/50319845-71470a80-0504-11e9-827b-f70b2e5f7b8e.png)

**Comment by SYFH** [comment]
应该是 GCD Timer 使用不当造成的, 我会在之后的版本修复

**Comment by SYFH** [comment]
来使用新版本吧, 如果还是有类似的问题, 请提交新的 Issue😉
