### ISSUE TITLE
tasks 筛选卡死

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#27]
![image](https://user-images.githubusercontent.com/10528244/50409503-28f25a00-082e-11e9-937f-8214d41b5456.png)

**Comment by SYFH** [comment]
系统方法不应该出现这种低级问题啊, 有可能是数量太多? 我之后测试一下

**Comment by SYFH** [comment]
来使用新版本吧, 如果还是有类似的问题, 请提交新的 Issue😉
