### ISSUE TITLE
URL 重定向问题

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#29]
当访问一个地址，比如： `www.xx.com/1.mp4` ，但是它的真实地址可能是： `www.yy.com/1.mp4`。由于是通过 url.identifier 来确定任务的，在 urlsession 的回调的时候获取`task.currentRequest.URL.absoluteString` 会得到后面的地址从而找不到该任务从而下载失败。

**Comment by huanglins** [comment]
可以通过 `task.originalRequest` 取到源地址进行处理

**Comment by huanglins** [comment]
`https://www.78pan.com/api/stats/hls/2018/05/10/qtEQzh1n/out005.ts`  这个地址可以看到重定向的效果

**Comment by SYFH** [comment]
现在直接使用 taskDescription 字段保存添加时的链接了, 属性本身支持 coding 协议, 问题基本解决, 如果还有问题可以再次提交 issue
