### ISSUE TITLE
demo 中下载列表里面侧滑删除一个已下载完成的cell没有删除本地缓存的文件。

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#3]
demo 中下载列表里面侧滑删除一个已下载完成的cell没有删除本地缓存的文件。

**Comment by SYFH** [comment]
你是想将已经下载完成的文件删除吗?

**Comment by huanglins** [comment]
是的




| |
vincent
|
|
邮箱：gvincent@163.com
|
在2018年12月05日 18:56，Norld 写道：

你是想将已经下载完成的文件删除吗?

**Comment by SYFH** [comment]
嗯, 目前 FKDownloader 是不负责在删除 FKTask 时, 删除已下载完成的文件, 需要自己删除文件.
可以在 `-[FKDownloadManager remove:]` 之前, 调用删除文件:
```
NSString *path = [[FKDownloadManager manager] acquire:url].filePath;
    if ([[NSFileManager defaultManager] fileExistsAtPath:path]) {
        NSError *error;
        [[NSFileManager defaultManager] removeItemAtPath:path error:&error];
        if (error) {
        NSLog(@"%@", error);
    }
}
```
也许之后我会在配置类添加删除文件的选项

**Comment by SYFH** [comment]
0.0.15 可以在配置实例上设置删除文件的选项, 只限于移除已完成任务操作. 其他情景就需要手动操作了
