### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by EdenChow** [SYFH/FKDownloader#30]
设备型号:iPhone 6
系统版本:10.2
操作步骤:运行demo，点击下载，再点击暂停，再点击取消
期望结果:正常
运行结果:崩溃
您的代码:无
![19510f20-cd8a-4307-92af-76c3d91d504d](https://user-images.githubusercontent.com/13067657/50672992-2fdf5080-1016-11e9-8222-54034b88cb4e.png)

**Comment by SYFH** [comment]
请将详细的崩溃信息发出来, 我这里测试没问题
