### ISSUE TITLE
连接电源后就可以直接下载 拔掉电源后下载就会停止

### ISSUE THREAD

**Issue by jianAjian** [SYFH/FKDownloader#32]
设备型号:iphone 7p
系统版本:iOS 12.1.4
操作步骤:运行demo 拔掉电源
期望结果:正常下载
运行结果:不下载
您的代码:无 
描述: 连接电源后就可以直接下载 拔掉电源后下载就会停止

**Comment by SYFH** [comment]
已修改, 版本已更新
