### ISSUE TITLE
有分片下载支持吗

### ISSUE THREAD

**Issue by zhuangtao97** [SYFH/FKDownloader#35]
设备型号:
系统版本:
操作步骤:
期望结果:
运行结果:
您的代码:

**Comment by SYFH** [comment]
项目本身并不直接支持分片下载, 因为分片下载需要的 NSURLSessionDataTask 不支持后台下载.
但可以在添加 task 时, 使用自定义 header 添加 range 字段, 因为必须保持 URL 唯一性, 所以链接需要一定的修改, 比如添加不影响使用参数表示第几个段.
