### ISSUE TITLE
pod版本 FKDownloader (0.1.3) 求助

### ISSUE THREAD

**Issue by BeijingCurvy** [SYFH/FKDownloader#36]
设备型号:iPhone6s Plus
系统版本:12.3.1
操作步骤:
收到长链接推送后添加下载任务。
期望结果:
能够按照给定的最大并发书数（3）以队列方式逐个完成下载。
运行结果:任务卡住，当正在执行的任务数量超过给定个数时提示超过最大并发数（貌似好像给定一个无法解析的链接进去的时候也不会报错，不返回结果，怀疑卡住和中间传入过错误链接有关系。）
您的代码:
didFinishLaunchingWithOptions中调用下面的方法
![image](https://user-images.githubusercontent.com/51810237/60313411-9627a900-9991-11e9-87ef-10168b5d69d9.png)
收到长链接推送后添加并开始任务的相关代码
![image](https://user-images.githubusercontent.com/51810237/60313372-73959000-9991-11e9-8880-b11aa1589ba3.png)
后台下载处理
![image](https://user-images.githubusercontent.com/51810237/60313491-edc61480-9991-11e9-8a7b-854a1da70909.png)
报错信息:（控制台输出）
![image](https://user-images.githubusercontent.com/51810237/60313074-498f9e00-9990-11e9-8985-375b82831beb.png)

**Comment by BeijingCurvy** [comment]
gai改了一下初始化
![image](https://user-images.githubusercontent.com/51810237/60314853-b86ff580-9996-11e9-8397-70e07bf1de13.png)
然后就这样了。。。。
![image](https://user-images.githubusercontent.com/51810237/60314799-8b234780-9996-11e9-8a0e-238d956ffdd0.png)

**Comment by SYFH** [comment]
第一个问题是个逻辑漏洞, 在处理完非200 http code后没有进行下一个任务.
第二个问题是处理block引用时没有使用标准的weak-strong dance, 导致在多线程下会出现weak=nil的BUG.
以上已全部在 0.1.4 中修复, 你可以再试试

**Comment by BeijingCurvy** [comment]
ok,刚刚看到，我这就试试，谢谢啦

**Comment by BeijingCurvy** [comment]
老铁，还是有BUG啊😂
异常定位
![image](https://user-images.githubusercontent.com/51810237/60706154-6c472700-9f3b-11e9-85e4-2716106d7a1d.png)
初始化代码
![image](https://user-images.githubusercontent.com/51810237/60706190-8123ba80-9f3b-11e9-9e5f-0920991dfdf8.png)

**Comment by BeijingCurvy** [comment]
改成这样

**Comment by SYFH** [comment]
当初的 `autoClearTask` 把自己坑了😂
只能先加一个判空处理直接返回了, 我现在四线操作有点太忙, 来不及细改了🙄

**Comment by SYFH** [comment]
来使用新版本吧, 如果还有类似的问题, 请再次提交 Issue😉
