### ISSUE TITLE
不能实现断点下载，暂停之后会从头开始下载

### ISSUE THREAD

**Issue by leeCoding** [SYFH/FKDownloader#37]
设备型号:iPhone 7
系统版本: 12+
操作步骤:使用http://d30.xcenable.com/storage/attachment/2019/8/14/4f9516f08b134a0c81a7c68247580a0f.mp4 下载视频，
期望结果:实现断点下载
运行结果:不能实现断点下载，暂停之后继续点击下载，会从头开始下载
您的代码:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/12134648/64596905-5e080200-d3e7-11e9-9098-38fe2a6bae13.png">

报错信息:我测试了下载发现我们公司的服务器下的资源都是这种情况，这两个方法 cancelByProducingResumeData 和 didCompleteWithError 里面的取的resumedata都为nil，不知道是什么原因

**Comment by SYFH** [comment]
如果不是个例, 那应该是服务器不支持断点续传, 比如不支持 Range HTTP Header, 你可以试一下网上其他的资源链接.
