### ISSUE TITLE
FKDownloadExecutor文件中 28行与83行两个不一致，这个是为什么啊

### ISSUE THREAD

**Issue by hponiang** [SYFH/FKDownloader#40]
设备型号:iphone 8
FKDownloadExecutor文件中 28行与83行两个不一致，这个是为什么啊
`
 FKTask *downloadTask = [[FKDownloadManager manager] acquire:url.absoluteString.decodeEscapedString];
`
`    FKTask *task = [[FKDownloadManager manager] acquire:url.absoluteString];
`

**Comment by SYFH** [comment]
嗯, 是大意了的过错😅
现在是全新的版本了, 来体验一下吧
