### ISSUE TITLE
该库还会更新吗？

### ISSUE THREAD

**Issue by leeCoding** [SYFH/FKDownloader#42]

**Comment by SYFH** [comment]
呃, 基本算植物人了, 偶尔蹦哒一下, 之后大概率会用 Swift 重构, 目前出现导致用不了的 BUG 会改一下, 精力已经严重不足了😭

**Comment by leeCoding** [comment]
这个我使用了一段时间，功能很丰富，我在原有的基础上加了开始时间和结束时间，也有几个问题不知道是我使用的方式不对还是其他原因，1.手动暂停之后，全部开始会出现不能再次开始的情况，目前发现的原因是在 tableView 数据源代理中返回 cell 中 设置 FKTask 再设置 setDelegate 又再次调用了暂停的方法 2.FKTask 里会出现 [FKTask retain] message sent to deallocated instance 奔溃，3.再移除监听任务 removeProgressObserver 这个方法，有时候会奔溃，4.任务的队列是无序的好像，number变量好像并不准确，有时会出现连续几个number 一样的情况，如果根据这个进行排序有问题，5.在FKTask 这个类中的 runTimer 有时候的会发生奔溃，如果有时间的希望能看下，我这边也跟踪看是否能找到奔溃的原因

**Comment by SYFH** [comment]
感谢🙏, 这些问题主要是当初设计简单, 功能也简单, 后来随着功能扩展就一发不可收拾了, 那些个文件都没用文件夹区分, 有些逻辑很冗余, 所以才想着要重构.
不过在用 Swift 重构前倒是可以先用 OC 试试, 我会再开一个新分支用来重构, 不过只能挤时间更新了.

**Comment by SYFH** [comment]
来了来了, 新版它来了🎉🎉🎉
不过, 与 0.x 有个区别可能会影响项目: 业务逻辑中的下载列表将由开发者管理, 毕竟 UI 上的显示不应该由第三方来控制.

**Comment by leeCoding** [comment]
我来看看
