### ISSUE TITLE
AFPercentEscapedStringFromString跟AFN冲突无法编译

### ISSUE THREAD

**Issue by walkmanaly** [SYFH/FKDownloader#43]
设备型号:
系统版本:
操作步骤:
期望结果:
运行结果:
您的代码:
报错信息:

**Comment by SYFH** [comment]
0.x 版本将不再更新, 请使用最新版本

**Comment by walkmanaly** [comment]
pod安装需要指定版本吗，谢谢

**Comment by SYFH** [comment]
可以使用 `pod update` 更新, `pod install` 可能会因为留有缓存而使用旧版本.
