### ISSUE TITLE
FKMessager 监听有时会出现监听不被移除的问题

### ISSUE THREAD

**Issue by MrBugDou** [SYFH/FKDownloader#44]
设备型号:iPhone7 Plus
系统版本:12.4.1
操作步骤:运行Demo，下载一个文件，进入下载管理页面，等待下载完成，完全退出Demo，再次运行Demo，直接打开下载管理页面。
期望结果: FKMessager messagerWithURL的监听回调只执行一次然后就移除监听，并且不在回调
运行结果:监听不会被移除，并且该Block代码块一直在被执行
您的代码:您的Demo，什么都没有改
报错信息:
![image](https://user-images.githubusercontent.com/12947653/78121556-1bb71880-743e-11ea-9fbc-6ff38c0c8064.png)

**Comment by SYFH** [comment]
从 FKMessager 的设计上来讲, 这个回调会一直被调用, 而这种因为已完成状态就只调用一次的逻辑, 可能导致轮询信息接收这个单一功能的逻辑被设计的过于复杂.
之后的版本会添加单次获取信息 API, 为了逻辑完善, 也会添加单独删除信息回调的 API.

**Comment by SYFH** [comment]
新版本已发布, 可以根据新 API 进行自定义调整

**Comment by MrBugDou** [comment]
离职了，刚看见，谢谢哈

**Comment by SYFH** [comment]
哈哈, 祝你之后工作顺利啊

**Comment by MrBugDou** [comment]
哈哈，抱拳了老铁
