### ISSUE TITLE
你好,导入头文件时#import "FKDownloader.h",调用下载方法,找不到文件'FKDownloader/FKConfigure.h' file not found

### ISSUE THREAD

**Issue by gu0315** [SYFH/FKDownloader#45]
设备型号:
系统版本:
操作步骤:
期望结果:
运行结果:
您的代码:
报错信息:
![image](https://user-images.githubusercontent.com/39515706/84236810-dcd2cc80-ab2a-11ea-837a-8b9fa6f763e5.png)

**Comment by SYFH** [comment]
可以提供下 Pods 版本吗?

**Comment by gu0315** [comment]
最新的版本,直接pod的,我后面没有添加版本号

**Comment by SYFH** [comment]
emmmm 难搞, 我这儿不管是使用本地路径, 还是线上版本, 都没有报错

**Comment by SYFH** [comment]
我先试试改下库的头文件和结构, 有可能因为 FKDownloader.h 这个文件被我直接扩展占用了有关系

**Comment by gu0315** [comment]
好吧,谢谢啦,我直接把你的代码克隆下来啦,直接在ViewController中添加#import "FKDownloader.h" 点用下载方法  addURL,就报找不到文件,必须调用下载方法才会报找不到文件

**Comment by SYFH** [comment]
好吧, 我刚刚更新了下版本, 便捷类已改名为 `FKDownloadTool.h`, 之前的头文件以还原为标准的库头文件了, 如果你要直接用源文件, 引用就得改成 `#import "FKDownloadTool.h"` 了

**Comment by SYFH** [comment]
更新版本后还有问题吗? 如果没问题我就关闭 issue 了
