### ISSUE TITLE
运用大侠库的时候 crash， 求解决，万分感谢！！！

### ISSUE THREAD

**Issue by heliang219** [SYFH/FKDownloader#46]
设备型号:iPhone
系统版本:13。5.1
操作步骤:demo 运行 资源列表 添加下载任务 添加了一屏幕多点 就是使得列表可以滑动 不管是在下载中还是下载完后 下载管理中上下多滑几次就会crash 必现 
期望结果:由于项目中用到了大侠的库，求解决，万分感谢
运行结果:
您的代码:
报错信息:Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <NSConcreteMapTable: 0x102613a10> was mutated while being enumerated.'

**Comment by SYFH** [comment]
问题已修复, 版本已更新到 1.0.11

**Comment by heliang219** [comment]
<img width="1368" alt="截屏2020-07-17 08 54 45" src="https://user-images.githubusercontent.com/795426/87736953-34d8af00-c80c-11ea-8986-44563d12ce6e.png">
还是一样 直接奔溃到这啊。。。

**Comment by SYFH** [comment]
版本已更新, 我自己测试已经没有再出现过类似错误了.

**Comment by heliang219** [comment]
还是奔溃 如图所示:
![截屏2020-07-18 22 46 17](https://user-images.githubusercontent.com/795426/87855107-b2093e80-c948-11ea-88f1-e9ab0724b399.png)

**Comment by heliang219** [comment]
我也是各种情况都会测下 不好意思 大侠 给你添麻烦了 还出现了这个奔溃 如图所示：
![截屏2020-07-18 22 58 13](https://user-images.githubusercontent.com/795426/87855354-458f3f00-c94a-11ea-82d7-e980e13e8e7a.png)

**Comment by SYFH** [comment]
可以提供下使用的代码吗? 我在 Demo 中复现不了这个错误, 也有可能是使用方法的问题

**Comment by heliang219** [comment]
代码我基本用的都是你demo里的 出现这个bug 是我点了多条下载的链接 可能是我手速过快导致

**Comment by SYFH** [comment]
可以用新版本再试试, 因为实在是复现不出来这个问题, 只能把可能出现问题的地方优化了
