### ISSUE TITLE
如何保存到本地文件的时候用原始文件名保存

### ISSUE THREAD

**Issue by heliang219** [SYFH/FKDownloader#48]
设备型号:  iPhone
系统版本:  iOS 11+
操作步骤:  文件下载后 保存到 "我的iPhone" 里的时候 得到的文件名不是原始文件名
期望结果: 
运行结果:
您的代码:
报错信息:

**Comment by heliang219** [comment]
![1](https://user-images.githubusercontent.com/795426/91409922-b9d9ce00-e878-11ea-93f7-4ea6fff934a0.jpg)
![2](https://user-images.githubusercontent.com/795426/91409933-bd6d5500-e878-11ea-9dac-58d2e01602c7.jpg)

**Comment by SYFH** [comment]
因为 URL 中可能不包含文件信息, 所以文件的名字是 MD5(URL), 后缀是 MIME Type.
如果需要重命名, 可在文件下载成功后通过`+[FKMessageer downloadedFilePathWithURL:]` 获取已下载文件的路径, 然后通过 `NSFileManager` 移动并重命名文件到指定的路径, 这一步操作和 `NSURLSession` 下载文件后的操作是一样的.

**Comment by heliang219** [comment]
好吧 谢谢了
