### ISSUE TITLE
总任务进度和分组任务进度不正确

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#5]
单个任务进度是正确的，汇总就会有一些问题
![image](https://user-images.githubusercontent.com/10528244/49625131-37a7d700-fa0f-11e8-9cbd-83a9c6c290ab.png)

**Comment by SYFH** [comment]
是根据 Tag 得到的 groupProgress 还是 FKDownloadManager.progress 总任务进度?
我是在 Demo 中测试没问题才更新版本的

**Comment by huanglins** [comment]
![image](https://user-images.githubusercontent.com/10528244/49631379-be1ee180-fa2c-11e8-85e3-b3dafb5cfaec.png)
我用的demo，tags 的任务进度好像是没问题的，总进度在第一个任务开始时没问题，开始第二个任务时，进度就大于1了。有时全部下载完成后，总进度又变成了 0 。

**Comment by SYFH** [comment]
任务总进度是使用 NSProgress 的父子关系实现的, 而不是像 Tags Group Progress 一样手动累计计算百分比. 父 NSProgress 会在子 NSProgress 达到 100% 时移除掉子进度, 大于 1 的问题晚上得用无线测试一下, 我白天只能用流量.

**Comment by SYFH** [comment]
任务总进度是使用 NSProgress 的父子关系实现的, 而不是像 Tags Group Progress 一样手动累计计算百分比. 父 NSProgress 会在子 NSProgress 达到 100% 时移除掉子进度, 大于 1 的问题晚上得用无线测试一下, 我白天只能用流量.

**Comment by SYFH** [comment]
0.1.0 版本使用了新的方式计算组进度, 还有因为不正常的赋值导致父 NSProgress 进度异常的问题也解决了.
