### ISSUE TITLE
时效性验证设置为可选项

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#6]
有的一组下载链接是通过参数来区别文件的，如果忽略参数设置 identifier 会导致这类任务无法添加。建议对该选项提供 configure 和 task 的设置。

**Comment by SYFH** [comment]
0.1.0 添加了是否忽略 URL 参数生成 Identifier 的选项, 默认为 NO, 也可通过 `FKTaskInfoIdentifierIgonerParameters` 单独控制.
