### ISSUE TITLE
请求过多造成主线程卡顿

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#7]
1. 一次添加比如100个 task，不停的归档会造成主线程卡死，直到所有任务添加完成。
2. 且开始执行任务后，执行过程中有明显卡顿。
3. groupProgress 计算错误，过多的 task 中，有时会往回跳。比如：0.5->0.55->0.2->0.6 这种。

**Comment by SYFH** [comment]
1. 目前的所有操作都在主线程上, 所以总会有卡顿, 下一步打算独立到特定的子线程中.
2. 同上, 不过最好用真机测试, 模拟器就连一个空白的 UITableView 都卡顿.
3. 因该是计算过程中有值改变导致的, 之后这个操作也会放到子线程中, 看情况应该得上锁.
4. 昨天加班到 12 点, 先缓缓, 先缓缓😂

**Comment by SYFH** [comment]
0.1.0 版本使用了新的方法添加任务组, 也改变了计算组进度的方法.
