### ISSUE TITLE
Demo 运行闪退

### ISSUE THREAD

**Issue by huanglins** [SYFH/FKDownloader#8]
![image](https://user-images.githubusercontent.com/10528244/49708051-ee52c400-fc68-11e8-9bf3-0b00abb88fe6.png)

**Comment by SYFH** [comment]
现在还在完善多线程与线程锁的问题, 估计内部结构会有很多大改动, 直到新的版本.
目前测试时最好将 App 删除后再测.

**Comment by SYFH** [comment]
已经添加了很多 TODO, 但这两天公司 App 要上线, 各种忙, 只能抽空更新了😭

**Comment by SYFH** [comment]
emmm 现在已经 0.1.0 版本了, 改动也不小, 旧版本还是删除后在进行测试吧
